// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text;
using Foundation;
using UIKit;

namespace mySafari.iOS
{
	public partial class WebViewController : UIViewController
	{
		public WebViewController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			//CallNativeFunction
			/*testWebView.LoadHtmlString (@"
			<html>
				<head>
					<title>Local String</title>
					<style type='text/css'>p{font-family : Verdana; color : purple }</style>
					<script language='JavaScript'> 
						function msg(){ 
							window.location = 'shirly://Hi'  
						}
					</script>
				</head>
				<body>
					<p>Hello World!</p><br />
					<button type='button' onclick='msg()' text='Hi'>Hi</button>
				</body>
			</html>", null);

			testWebView.ShouldStartLoad = 
				delegate(UIWebView webView, 
					NSUrlRequest request, 
					UIWebViewNavigationType navigationType) {

				var requestString = request.Url.AbsoluteString;

				var components = requestString.Split ( new[]{ @"://"}, StringSplitOptions.None);

				if (components.Length > 1 && components [0].ToLower() == @"shirly".ToLower()) {

					if (components [1] == @"Hi") {

						UIAlertController alert = UIAlertController.Create (@"Hi Title", @"當然是世界好", UIAlertControllerStyle.Alert);


						UIAlertAction okAction = UIAlertAction.Create (@"OK", UIAlertActionStyle.Default, (action) => {
							Console.WriteLine(@"OK");
						});
						alert.AddAction (okAction);


						UIAlertAction cancelAction = UIAlertAction.Create (@"Cancel", UIAlertActionStyle.Default, (action) =>{
							Console.WriteLine(@"Cancel");
						});
						alert.AddAction (cancelAction);

						PresentViewController (alert, true, null);


						return false;
					}

				}

				return true;

			};
*/
			//CallPageFunction
			testWebView.LoadHtmlString (@"<html><head><title>Local String</title><style type='text/css'>p{font-family : Verdana; color : purple }</style><script language='JavaScript'> function msg( text ){alert( text );}</script></head><body><p>Hello World!</p><br /><button type='button' onclick='msg()' text='Hi'>Hi</button></body></html>", null);

			btnMessage.TouchUpInside += (object sender, EventArgs e) => {
				var message = new StringBuilder(@"msg('");

				message.Append( txtMessage.Text );
				message.Append(@"')");

				testWebView.EvaluateJavascript(message.ToString() );
				
			};

		}


	}
}
